package org.securemail.ui;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import javafx.application.Platform;
import javafx.scene.*;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.*;
import org.securemail.client.*;
import org.securemail.client.appearance.*;
import org.securemail.client.storage.*;
import org.securemail.client.update.*;
import static org.securemail.client.appearance.Appearance.*;
/** Actual JavaFX objects, CSS, dialog routing and screenshots. Headless, not native acceptance. */
public final class Appearance115Smoke {
  static Settings change(Settings s,String section,String key,String value)throws Exception{var json=s.json();json.getAsJsonObject(section).addProperty(key,value);return Settings.parse(json);}
  static void screenshot(Stage stage,String name)throws Exception{Parent root=stage.getScene().getRoot();root.applyCss();root.layout();var image=root.snapshot(null,null);var pixels=image.getPixelReader();var buffered=new java.awt.image.BufferedImage((int)image.getWidth(),(int)image.getHeight(),java.awt.image.BufferedImage.TYPE_INT_ARGB);for(int y=0;y<buffered.getHeight();y++)for(int x=0;x<buffered.getWidth();x++)buffered.setRGB(x,y,pixels.getArgb(x,y));Path folder=Path.of("build/ui115-screenshots");Files.createDirectories(folder);javax.imageio.ImageIO.write(buffered,"png",folder.resolve(name+".png").toFile());}
  static Button button(Stage stage,String name){return stage.getScene().getRoot().lookupAll(".button").stream().filter(n->n instanceof Button b&&name.equals(b.getText())).map(n->(Button)n).findFirst().orElseThrow();}
  public static void main(String[] args)throws Exception{
    Path profile=Files.createTempDirectory("AEGIS-115-UI-");System.setProperty("aegis.profile",profile.toString());Platform.startup(()->Platform.setImplicitExit(false));
    var config=ClientConfig.load(profile.resolve("config/client.properties"));var session=new ClientSession(config,"synthetic-ui-only-vault-pass".toCharArray());session.local().bindNickname("raven");MessengerApp app=MessengerSmoke.fx(MessengerApp::new);
    Stage stage=MessengerSmoke.fx(()->{Stage window=new Stage();window.initStyle(StageStyle.UNDECORATED);BorderPane root=new BorderPane();BorderPane outer=new BorderPane(root);outer.setTop(new WindowChrome(window));window.setScene(new Scene(outer,1280,900));InWindowDialog.bind(window,outer);MessengerSmoke.set(app,"stage",window);MessengerSmoke.set(app,"root",root);MessengerSmoke.set(app,"config",config);MessengerSmoke.set(app,"session",session);MessengerSmoke.set(app,"presets",new UiPresetStore(profile));MessengerSmoke.set(app,"updates",new UpdateService(profile,19052));MessengerSmoke.set(app,"updatePreferences",UpdatePreferences.load(profile));ThemeManager themes=(ThemeManager)MessengerSmoke.get(app,"themes");themes.initialize();themes.apply(outer);themes.apply(root);themes.track(window.getScene());themes.workspace(root);themes.listener(s->{try{Aegis11UiSmoke.invoke(app,"appearanceChanged",new Class<?>[]{Settings.class},s);}catch(Exception e){throw new RuntimeException(e);}});window.show();app.mainPage();return window;});
    try{MessengerSmoke.fx(()->{ThemeManager t=(ThemeManager)MessengerSmoke.get(app,"themes");app.composePage();TextArea draft=(TextArea)MessengerSmoke.get(app,"composer");draft.setText("Длинный черновик: кириллица, Latin, long-nickname-123456789. Состояние сохраняется.");String text=draft.getText();long started=System.nanoTime();int count=0;for(Theme preset:PresetLibrary.builtins().values()){t.commit(t.settings().manual(preset.id()));stage.getScene().getRoot().applyCss();stage.getScene().getRoot().layout();MessengerSmoke.check(draft.getText().equals(text),"Theme lost draft");MessengerSmoke.check(t.visualTheme().id().equals(preset.id()),"Preset not applied");count++;if(List.of("minimal-dark","deep-blue","frost-blue","classic-light").contains(preset.id()))screenshot(stage,preset.id());}System.out.println("UI-01/24 rendered "+count+" presets with unchanged draft in "+((System.nanoTime()-started)/1000000)+" ms");
      Settings before=t.settings();byte[] disk=Files.readAllBytes(t.store().root().resolve("settings.json"));t.preview(before.manual("forest-green"));MessengerSmoke.check(!t.visualTheme().id().equals(before.theme()),"Preview not visible");MessengerSmoke.check(Arrays.equals(disk,Files.readAllBytes(t.store().root().resolve("settings.json"))),"Preview persisted early");t.cancelPreview();MessengerSmoke.check(t.settings().equals(before),"Cancel failed");
      for(Composer mode:Composer.values()){t.commit(change(t.settings(),"layout","composer",mode.name()));MessengerSmoke.check(draft.getText().equals(text),"Composer mode lost draft");}
      for(int scale:List.of(100,125,150,200)){var j=t.settings().json();j.addProperty("scale",scale);t.commit(Settings.parse(j));MessengerSmoke.check(draft.getText().equals(text),"Scale lost draft");stage.getScene().getRoot().applyCss();stage.getScene().getRoot().layout();}var j=t.settings().json();j.addProperty("scale",100);t.commit(Settings.parse(j));
      app.mailboxPage(false);for(Zone zone:Zone.values())for(Labels labels:Labels.values()){Settings s=change(t.settings(),"layout","zone",zone.name());s=change(s,"layout","labels",labels.name());t.commit(s);stage.getScene().getRoot().applyCss();stage.getScene().getRoot().layout();MessengerSmoke.check(((BorderPane)MessengerSmoke.get(app,"root")).getChildrenUnmodifiable().stream().flatMap(n->(n instanceof ScrollPane sp?sp.getContent():n).lookupAll(".nav-item").stream()).anyMatch(n->n instanceof Button b&&"Настройки".equals(b.getAccessibleText())),"Settings unreachable");}
      for(MailLayout layout:MailLayout.values()){t.commit(change(t.settings(),"layout","mail",layout.name()));stage.getScene().getRoot().applyCss();stage.getScene().getRoot().layout();MessengerSmoke.check(((BorderPane)MessengerSmoke.get(app,"root")).getCenter()!=null,"Mail center missing");}
      for(Rows rows:Rows.values())t.commit(change(t.settings(),"layout","rows",rows.name()));t.commit(defaults().manual("deep-blue"));app.mailboxPage(false);screenshot(stage,"mail-center");
      stage.setWidth(640);stage.setHeight(520);stage.getScene().getRoot().applyCss();stage.getScene().getRoot().layout();MessengerSmoke.check(((BorderPane)MessengerSmoke.get(app,"root")).getCenter()!=null,"Narrow window lost actions");stage.setWidth(1280);stage.setHeight(900);
      Aegis11UiSmoke.invoke(app,"appearance",new Class<?>[]{});stage.getScene().getRoot().applyCss();stage.getScene().getRoot().layout();screenshot(stage,"appearance-gallery");button(stage,"Forest Green").fire();button(stage,"Применить").fire();MessengerSmoke.check(t.store().current().theme().equals("forest-green"),"Real gallery Apply failed");MessengerSmoke.check(new AppearanceStore(profile).current().theme().equals("forest-green"),"Restart state not saved");
      Aegis11UiSmoke.invoke(app,"settings",new Class<?>[]{});screenshot(stage,"settings");InWindowDialog.closeAll(stage);Aegis11UiSmoke.invoke(app,"systemLetters",new Class<?>[]{});screenshot(stage,"system-empty");
      MessengerSmoke.check(Window.getWindows().stream().filter(w->w instanceof Stage&&w.isShowing()).count()==1,"Appearance opened another system window");System.out.println("UI-03/04/13/14/18/19/20/24/25/26/29 PASS; logical scale tested 100/125/150/200, physical DPI NOT_RUN");return null;});}finally{MessengerSmoke.fx(()->{app.stop();return null;});}
  }
}
