package org.securemail.client.appearance;
import static org.junit.jupiter.api.Assertions.*;
import static org.securemail.client.appearance.Appearance.*;
import com.google.gson.*;
import java.io.*;
import java.nio.file.*;
import java.time.LocalTime;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.securemail.client.storage.*;
import org.securemail.client.update.JsonData;
class AppearanceTest {
  @TempDir Path root;
  @Test void sixteenCategoriesAndAllLegacyPalettesRemainReadable(){assertEquals(22,PresetLibrary.builtins().size());for(Category c:new Category[]{Category.MINIMAL,Category.DEPTH,Category.TRANSPARENT,Category.CLASSIC})assertEquals(4,PresetLibrary.builtins().values().stream().filter(t->t.category()==c).count());for(Theme t:PresetLibrary.builtins().values()){assertTrue(contrast(t.palette().text(),t.palette().panel())>=4.5);assertTrue(contrast(t.palette().text(),t.palette().incoming())>=4.5);assertTrue(contrast(t.palette().text(),t.palette().outgoing())>=4.5);}assertEquals("#0c1812",PresetLibrary.get("legacy-dark-green").palette().background());}
  @Test void migrateGreenAndBottomWithoutChangingOldFiles()throws Exception{new UiPresetStore(root).apply(new UiPreferences(150,UiPreferences.Density.COMPACT,true,UiPreferences.Avatars.SMALL,UiPreferences.Preview.BOTTOM,true,true));Files.writeString(root.resolve("theme.txt"),"DARK_GREEN");byte[] old=Files.readAllBytes(root.resolve("ui-preferences.json"));AppearanceStore s=new AppearanceStore(root);assertEquals("legacy-dark-green",s.current().theme());assertEquals(150,s.current().scale());assertTrue(s.current().layout().previewBelow());assertEquals("#0c1812",s.current().backdrop().color());assertArrayEquals(old,Files.readAllBytes(root.resolve("ui-preferences.json")));assertArrayEquals(old,Files.readAllBytes(root.resolve("appearance/migration-1.1.1/ui-preferences.json")));assertEquals(s.current(),new AppearanceStore(root).current());}
  @Test void settingsAreAtomicAndRestorePreviousAppearance()throws Exception{AppearanceStore s=new AppearanceStore(root);Settings before=s.current(),next=before.manual("forest-green");s.apply(next);assertEquals(next,new AppearanceStore(root).current());s.restoreBackup();assertEquals(before,s.current());assertTrue(Files.exists(root.resolve("appearance/settings.failed.json")));}
  @Test void damagedAndIncompatibleFilesArePreservedInSafeMode()throws Exception{AppearanceStore s=new AppearanceStore(root);Path p=s.root().resolve("settings.json");Files.writeString(p,"{broken");AppearanceStore corrupt=new AppearanceStore(root);assertEquals(defaults(),corrupt.current());assertFalse(corrupt.recovery().isEmpty());assertEquals("{broken",Files.readString(p));Files.writeString(p,"{\"schema\":99}");assertFalse(new AppearanceStore(root).recovery().isEmpty());}
  @Test void builtinImmutableAndCustomRoundTripHasNoSecrets()throws Exception{AppearanceStore s=new AppearanceStore(root);assertThrows(IOException.class,()->s.renameTheme("minimal-dark","changed"));assertThrows(IOException.class,()->s.removeTheme("legacy-dark-green"));Theme t=PresetLibrary.get("forest-green").copy("Моя тема");s.addTheme(t,s.current().manual("forest-green").manual(t.id()));Path p=root.resolve("theme.json");s.exportTheme(t.id(),p);String json=Files.readString(p);for(String banned:new String[]{"password","privateKey","ciphertext","url","css"})assertFalse(json.contains(banned));AppearanceStore second=new AppearanceStore(root.resolve("second"));Theme imported=second.importTheme(p);assertEquals(t.palette(),imported.palette());assertEquals(Category.CUSTOM,imported.category());s.renameTheme(t.id(),"Тема 2");assertEquals("Тема 2",new AppearanceStore(root).theme(t.id()).name());s.removeTheme(t.id());assertNull(s.theme(t.id()));}
  @Test void layoutsReorderRequiredActionsAndRetainSettingsAccess()throws Exception{AppearanceStore s=new AppearanceStore(root);Layout l=defaults().layout();s.saveLayout("Почта",l.panels(20,40));Path p=root.resolve("layout.json");s.exportLayout("Почта",p);AppearanceStore other=new AppearanceStore(root.resolve("other"));other.importLayout(p);assertEquals(l.panels(20,40),other.layouts().get("Почта"));JsonObject o=l.json();o.getAsJsonArray("order").remove(5);assertThrows(IOException.class,()->Layout.parse(o));s.renameLayout("Почта","Работа");assertTrue(new AppearanceStore(root).layouts().containsKey("Работа"));s.removeLayout("Работа");assertTrue(s.layouts().isEmpty());}
  @Test void importsRejectCodeUrlsUnknownKeysAndOversize()throws Exception{AppearanceStore s=new AppearanceStore(root);Path p=root.resolve("bad.json");Files.writeString(p,"{\"schema\":1,\"kind\":\"aegis-theme\",\"css\":\"url(https://example.invalid)\"}");assertThrows(IOException.class,()->s.importTheme(p));Files.write(p,new byte[MAX_JSON+1]);assertThrows(IOException.class,()->s.importTheme(p));JsonObject settings=defaults().json();settings.addProperty("password","secret");assertThrows(IOException.class,()->Settings.parse(settings));JsonObject font=defaults().typography().mail().json();font.addProperty("family","System';-fx-background:url(x)");assertThrows(IOException.class,()->Type.parse(font));assertThrows(IllegalArgumentException.class,()->new Backdrop(Background.IMAGE,"#000000","#000000","../../password"));}
  @Test void unreadablePaletteAndBackdropCannotBeSaved()throws Exception{assertThrows(IllegalArgumentException.class,()->new Palette("#000000","#000000","#000000","#000000","#000000","#000000","#000000","#000000"));AppearanceStore s=new AppearanceStore(root);Settings before=s.current();assertThrows(IOException.class,()->s.apply(s.current().manual("minimal-dark").backdrop(new Backdrop(Background.SOLID,"#ffffff","#ffffff",""))));assertEquals(before,s.current());}
  @Test void scheduleHandlesMidnightAndOsMode()throws Exception{Settings d=defaults();Settings s=new Settings(d.theme(),Mode.SCHEDULE,"minimal-light","forest-green","20:00","07:00",d.scale(),d.density(),d.typography(),d.components(),d.layout(),d.backdrop());assertEquals("minimal-light",effectiveTheme(s,false,LocalTime.of(23,0)));assertEquals("forest-green",effectiveTheme(s,true,LocalTime.of(12,0)));Settings sys=new Settings(d.theme(),Mode.SYSTEM,s.lightTheme(),s.darkTheme(),s.lightAt(),s.darkAt(),d.scale(),d.density(),d.typography(),d.components(),d.layout(),d.backdrop());assertEquals("minimal-light",effectiveTheme(sys,true,LocalTime.NOON));assertEquals("forest-green",effectiveTheme(sys,false,LocalTime.NOON));}
  @Test void imageTypeSizeAndStoredPathAreBounded()throws Exception{BufferedImage im=new BufferedImage(3000,100,BufferedImage.TYPE_INT_RGB);ByteArrayOutputStream out=new ByteArrayOutputStream();ImageIO.write(im,"png",out);byte[] normalized=BackgroundCodec.normalize(out.toByteArray());BufferedImage result=ImageIO.read(new ByteArrayInputStream(normalized));assertTrue(result.getWidth()<=BackgroundCodec.MAX_SIDE);AppearanceStore s=new AppearanceStore(root);String id=s.image(normalized);assertTrue(s.imagePath(id).startsWith(s.root()));assertThrows(IOException.class,()->s.imagePath("../bad"));assertThrows(IOException.class,()->BackgroundCodec.normalize(new byte[5*1024*1024+1]));assertThrows(IOException.class,()->BackgroundCodec.normalize("<script>bad</script>".getBytes()));}
  @Test void favoritesPersistWithoutMutatingBuiltins()throws Exception{AppearanceStore s=new AppearanceStore(root);Theme original=s.theme("minimal-dark");s.favorite(original.id(),true);assertTrue(new AppearanceStore(root).favorites().contains(original.id()));assertEquals(original,s.theme(original.id()));s.favorite(original.id(),false);assertFalse(s.favorites().contains(original.id()));}
}
