package org.securemail.ui;
import javafx.geometry.Insets;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;
import org.securemail.client.update.*;
import java.util.*;
import java.util.function.*;

/** One primary action, reflecting the actual verified updater state. */
final class UpdatesView {
  private final InWindowDialog<Void> dialog=new InWindowDialog<>();private final Label state=new Label(),bytes=new Label(),technical=new Label();private final ProgressBar progress=new ProgressBar();
  private final Button action=new Button(),notes=new Button("Что нового"),cancel=new Button("Отменить"),detailsAction=new Button("Проверить снова");private final UpdateService service;private final Runnable installAction;private final CheckBox fetch;
  UpdatesView(Stage owner,ThemeManager themes,UpdateService service,UpdatePreferences preferences,Consumer<UpdatePreferences> save,Runnable installAction){
    this.service=service;this.installAction=installAction;dialog.initOwner(owner);dialog.setTitle("Обновления");dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);
    Selector<String> channel=new Selector<>(themes,List.of("Stable","Beta"),preferences.channel().equals("stable")?"Stable":"Beta");
    CheckBox automatic=new CheckBox("Проверять при запуске и раз в сутки");fetch=new CheckBox("Скачивать автоматически");CheckBox exit=new CheckBox("Устанавливать при закрытии");automatic.setSelected(preferences.automaticCheck());fetch.setSelected(preferences.automaticDownload());exit.setSelected(preferences.installAtExit());
    Runnable persist=()->{try{save.accept(new UpdatePreferences(channel.getValue().toLowerCase(Locale.ROOT),automatic.isSelected(),fetch.isSelected(),exit.isSelected()));refresh(service.snapshot());}catch(RuntimeException failure){state.setText("Настройки нельзя изменить во время операции");}};
    channel.valueProperty().addListener((o,a,b)->persist.run());automatic.setOnAction(e->persist.run());fetch.setOnAction(e->persist.run());exit.setOnAction(e->persist.run());action.getStyleClass().add("primary");action.setOnAction(e->perform());detailsAction.setOnAction(e->service.check(fetch.isSelected()));
    notes.setOnAction(e->{var s=service.snapshot();if(s.manifest()!=null)notes(owner,themes,s.manifest());});cancel.setOnAction(e->service.cancel());
    Button history=new Button("История обновлений");history.setOnAction(e->{ListView<String> items=new ListView<>();items.setPlaceholder(new Label("История пуста"));InWindowDialog<Void> view=new InWindowDialog<>();view.initOwner(owner);view.setTitle("История обновлений");view.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);view.getDialogPane().setContent(items);themes.apply(view.getDialogPane());view.show();Thread loader=new Thread(()->{try{var records=service.events().stream().map(UpdatesView::eventText).toList();javafx.application.Platform.runLater(()->items.getItems().setAll(records));}catch(Exception failure){javafx.application.Platform.runLater(()->items.setPlaceholder(new Label("История недоступна")));}},"aegis-history");loader.setDaemon(true);loader.start();});
    technical.setWrapText(true);TitledPane details=new TitledPane("Подробности",new VBox(8,technical,detailsAction));details.setExpanded(false);progress.setMaxWidth(Double.MAX_VALUE);VBox box=new VBox(12,new Label("АЕГИС "+SignedManifest.CURRENT),new HBox(10,new Label("Канал"),channel),state,bytes,progress,new HBox(8,action,notes,cancel),new Separator(),automatic,fetch,exit,history,details);box.setPrefWidth(440);box.setPadding(new Insets(16));dialog.getDialogPane().setContent(box);themes.apply(dialog.getDialogPane());refresh(service.snapshot());
  }
  private void perform(){var s=service.snapshot();switch(s.state()){case READY_TO_INSTALL->{dialog.close();installAction.run();}case AVAILABLE->service.download();case FAILED->{if(s.manifest()!=null)service.download();else service.check(fetch.isSelected());}case UP_TO_DATE->service.check(fetch.isSelected());default->{}}}
  static String eventText(UpdateEvents.Event e){String kind=switch(e.kind()){case AVAILABLE->"Обновление обнаружено";case DOWNLOADED->"Скачано";case VERIFIED->"Проверка пройдена";case INSTALLED->"Установка завершена";case RESTARTED->"Перезапуск подтверждён";case FAILED->"Ошибка обновления";case ROLLBACK->"Выполнен откат";};return e.time()+" · "+e.channel()+" · "+e.version()+"\n"+kind+(e.code().isEmpty()?"":" · "+e.code());}
  void refresh(UpdateService.Snapshot s){state.setText(s.message());technical.setText(s.diagnostic()==null?"Ошибок нет":s.diagnostic().technical());boolean fetching=s.state()==UpdateService.State.DOWNLOADING;boolean busy=Set.of(UpdateService.State.CHECKING,UpdateService.State.DOWNLOADING,UpdateService.State.VERIFYING,UpdateService.State.INSTALLING,UpdateService.State.RESTARTING).contains(s.state());action.setText(switch(s.state()){case AVAILABLE->"Обновить";case DOWNLOADING->"Скачивание…";case VERIFYING->"Проверка подписи и SHA-256…";case READY_TO_INSTALL->"Установить и перезапустить";case INSTALLING->"Подготовка…";case RESTARTING->"Перезапуск…";case CHECKING->"Проверка…";case FAILED->"Повторить";case UP_TO_DATE->"Проверить обновления";});action.setDisable(busy);detailsAction.setDisable(busy);notes.setDisable(s.manifest()==null);cancel.setVisible(fetching);cancel.setManaged(fetching);progress.setVisible(fetching);progress.setManaged(fetching);progress.setProgress(s.total()>0?Math.min(1,(double)s.downloaded()/s.total()):0);bytes.setText(fetching?String.format(Locale.ROOT,"%.1f / %.1f МБ · %.0f%%",s.downloaded()/1048576.0,s.total()/1048576.0,s.total()>0?100.0*s.downloaded()/s.total():0):"");}
  void show(){dialog.show();}boolean showing(){return dialog.isShowing();}
  static void notes(Stage owner,ThemeManager themes,SignedManifest manifest){InWindowDialog<Void> d=new InWindowDialog<>();d.initOwner(owner);d.setTitle("Что нового · "+manifest.version());d.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);TextArea text=new TextArea(manifest.releaseNotes().text());text.setEditable(false);text.setWrapText(true);text.setPrefRowCount(14);Label title=new Label(manifest.announcement().title());title.setWrapText(true);Label link=new Label(manifest.changelog().url().toString());link.setWrapText(true);d.getDialogPane().setContent(new VBox(10,title,text,link));themes.apply(d.getDialogPane());d.show();}
}
