package org.securemail.client.update;

import static org.junit.jupiter.api.Assertions.*;
import com.google.gson.*;
import java.io.*;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import java.util.zip.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;

/** Test keys are generated in memory and never replace the production trust key. */
class UpdateSecurityTest {
  @TempDir Path root;KeyPair pair;byte[] archive;
  @BeforeEach void setup()throws Exception{pair=KeyPairGenerator.getInstance("Ed25519").generateKeyPair();archive=zip(false);}
  byte[] zip(boolean traversal)throws IOException{ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(ZipOutputStream z=new ZipOutputStream(bytes)){for(String name:List.of("AEGIS.exe","AEGIS-Updater.exe","runtime/bin/javaw.exe","tor/tor.exe","tor/pluggable_transports/lyrebird.exe","native/libsodium.dll","app/client-core-1.1.1.jar","app/client-ui-1.1.1.jar","app/common-protocol-0.2.0.jar")){z.putNextEntry(new ZipEntry("AEGIS/"+name));z.write(("test fixture "+name).getBytes(StandardCharsets.US_ASCII));z.closeEntry();}if(traversal){z.putNextEntry(new ZipEntry("AEGIS/../escaped"));z.write(1);z.closeEntry();}}return bytes.toByteArray();}
  JsonObject doc()throws Exception{
    JsonObject o=new JsonObject();o.addProperty("schemaVersion",1);o.addProperty("application","AEGIS");o.addProperty("channel","stable");o.addProperty("version","1.1.1");o.addProperty("tag","v1.1.1");o.addProperty("repository",SignedManifest.REPOSITORY);o.addProperty("protocolVersion",1);JsonArray relay=new JsonArray();relay.add("0.2.0");o.add("relayCompatibility",relay);o.addProperty("minimumSupported","1.0.0");o.addProperty("updatePolicy","optional");JsonObject a=new JsonObject();a.addProperty("title","Обновление АЕГИС 1.1.1");a.addProperty("summary","Исправления");a.addProperty("showAsLetter",true);o.add("announcement",a);JsonObject n=new JsonObject();n.addProperty("publishedAt","2026-10-08T00:00:00Z");n.addProperty("type","Fix");n.addProperty("text","Проверенные исправления");o.add("releaseNotes",n);JsonArray files=new JsonArray();
    files.add(asset("AEGIS-Setup-1.1.1-x64.exe","windows-x64","installer"));files.add(asset("AEGIS-1.1.1-Windows-x64.zip","windows-x64","portable"));files.add(asset("AEGIS-1.1.1-CachyOS-x86_64.AppImage","cachyos-x86_64","appimage"));files.add(asset("AEGIS-1.1.1-client-source.zip","source","source"));o.add("artifacts",files);o.add("checksums",asset("SHA256SUMS",null,null));o.add("changelog",asset("CHANGELOG-1.1.1.md",null,null));return o;
  }
  JsonObject asset(String name,String platform,String kind)throws Exception{JsonObject a=new JsonObject();a.addProperty("fileName",name);a.addProperty("size",archive.length);a.addProperty("sha256",HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(archive)));a.addProperty("url","https://github.com/"+SignedManifest.REPOSITORY+"/releases/download/v1.1.1/"+name);if(platform!=null){a.addProperty("platform",platform);a.addProperty("kind",kind);}return a;}
  byte[] sign(byte[] bytes)throws Exception{Signature signature=Signature.getInstance("Ed25519");signature.initSign(pair.getPrivate());signature.update(bytes);return signature.sign();}
  SignedManifest verify(byte[] data,byte[] signature)throws Exception{return SignedManifest.verifyWithKey(data,signature,"stable","1.0.0","1.0.0",pair.getPublic());}
  SignedManifest verified(JsonObject o)throws Exception{byte[] bytes=JsonData.encode(o);return verify(bytes,sign(bytes));}
  @Test void validExactSignatureAcceptsAndPinsProductionKey()throws Exception{byte[] data=JsonData.encode(doc());assertEquals("1.1.1",verify(data,sign(data)).version());assertEquals("MCowBQYDK2VwAyEAswWYCFStSEhQdrgqUJFF3x12ltmfUA0PvQtlh684B2g=",Base64.getEncoder().encodeToString(SignedManifest.embeddedPublicKey()));assertThrows(SignatureException.class,()->SignedManifest.verify(data,sign(data),"stable","1.0.0","1.0.0"));byte[] key=SignedManifest.embeddedPublicKey();key[0]^=1;assertNotEquals(key[0],SignedManifest.embeddedPublicKey()[0]);}
  @Test void changedJsonAndUnparseableUnsignedDataFailSignatureFirst()throws Exception{byte[] data=JsonData.encode(doc()),sig=sign(data);data[0]^=1;assertThrows(SignatureException.class,()->verify(data,sig));byte[] bad="not JSON".getBytes(StandardCharsets.US_ASCII);assertThrows(SignatureException.class,()->verify(bad,new byte[64]));assertThrows(IOException.class,()->verify(bad,sign(bad)));}
  @Test void wrongSignatureAndKeyRejected()throws Exception{byte[] data=JsonData.encode(doc()),sig=sign(data);sig[9]^=1;assertThrows(GeneralSecurityException.class,()->verify(data,sig));KeyPair wrong=KeyPairGenerator.getInstance("Ed25519").generateKeyPair();assertThrows(GeneralSecurityException.class,()->SignedManifest.verifyWithKey(data,sign(data),"stable","1.0.0","1.0.0",wrong.getPublic()));}
  @Test void duplicateAndUnknownJsonFieldsRejectedEvenIfSigned()throws Exception{String json=new String(JsonData.encode(doc()),StandardCharsets.UTF_8);byte[] duplicate=json.replace("\"schemaVersion\": 1","\"schemaVersion\": 1, \"schemaVersion\": 1").getBytes(StandardCharsets.UTF_8);assertThrows(IOException.class,()->verify(duplicate,sign(duplicate)));JsonObject unknown=doc();unknown.addProperty("command","run");assertThrows(IOException.class,()->verified(unknown));}
  @Test void channelProtocolUrlAndDateAreStrict()throws Exception{JsonObject o=doc();o.addProperty("channel","beta");assertThrows(IOException.class,()->verified(o));JsonObject p=doc();p.addProperty("protocolVersion",2);assertThrows(IOException.class,()->verified(p));JsonObject u=doc();u.getAsJsonArray("artifacts").get(1).getAsJsonObject().addProperty("url","https://example.invalid/malware");assertThrows(IOException.class,()->verified(u));JsonObject date=doc();date.getAsJsonObject("releaseNotes").addProperty("publishedAt","today");assertThrows(IOException.class,()->verified(date));}
  @Test void downgradeAndSignedSameVersionReplacementRejected()throws Exception{byte[] bytes=JsonData.encode(doc()),sig=sign(bytes);assertThrows(IOException.class,()->SignedManifest.verifyWithKey(bytes,sig,"stable","1.1.2","1.1.2",pair.getPublic()));UpdateStateStore store=new UpdateStateStore(root);SignedManifest manifest=verify(bytes,sig);store.remember(manifest,bytes,sig);JsonObject changed=doc();changed.getAsJsonObject("announcement").addProperty("summary","Replaced");byte[] next=JsonData.encode(changed);assertThrows(IOException.class,()->store.remember(verify(next,sign(next)),next,sign(next)));}
  @Test void requiredOnlySecurityOrIncompatibleAndOptionalDoesNotGate()throws Exception{assertFalse(verified(doc()).requiredFor("1.0.0"));JsonObject o=doc();o.addProperty("updatePolicy","required");assertThrows(IOException.class,()->verified(o));o.getAsJsonObject("releaseNotes").addProperty("type","Security");assertTrue(verified(o).requiredFor("1.0.0"));JsonObject incompatible=doc();incompatible.addProperty("minimumSupported","1.1.1");incompatible.addProperty("updatePolicy","required");assertTrue(verified(incompatible).requiredFor("1.0.0"));}
  @Test void announcementDeduplicatesAndTamperingNeverEntersTrustedHistory()throws Exception{UpdateStateStore store=new UpdateStateStore(root);byte[] bytes=JsonData.encode(doc()),sig=sign(bytes);SignedManifest manifest=verify(bytes,sig);assertTrue(store.remember(manifest,bytes,sig));store.announcementShown(manifest);assertFalse(store.remember(manifest,bytes,sig));assertTrue(store.history("stable").isEmpty(),"ephemeral key must not be trusted by production history");Files.writeString(store.root().resolve("stable-99.0.0.json"),"{}");assertTrue(store.history("stable").isEmpty());}
  @Test void binaryChangedWrongSizeAndTraversalRejected()throws Exception{SignedManifest m=verified(doc());Path p=root.resolve("update.zip");Files.write(p,archive);UpdateService.verifyFile(p,m.clientAsset(true));PackageSanity.check(p,m.clientAsset(true),m.version());byte[] changed=archive.clone();changed[0]^=1;Files.write(p,changed);assertThrows(GeneralSecurityException.class,()->UpdateService.verifyFile(p,m.clientAsset(true)));Files.write(p,new byte[3]);assertThrows(IOException.class,()->UpdateService.verifyFile(p,m.clientAsset(true)));archive=zip(true);Files.write(p,archive);SignedManifest bad=verified(doc());assertThrows(IOException.class,()->PackageSanity.check(p,bad.clientAsset(true),bad.version()));assertFalse(Files.exists(root.resolve("escaped")));}
  @Test void semanticPrereleaseOrderingAndLimits(){assertTrue(SemVersion.parse("1.0.0-beta.10").compareTo(SemVersion.parse("1.0.0-beta.2"))>0);assertTrue(SemVersion.parse("1.0.0").compareTo(SemVersion.parse("1.0.0-rc.1"))>0);assertThrows(IllegalArgumentException.class,()->SemVersion.parse("1.00.0"));assertThrows(IllegalArgumentException.class,()->SemVersion.parse("1.0.0-beta.01"));}
  UpdateService service(UpdateService.Downloads downloads)throws Exception{return new UpdateService(downloads,new UpdateStateStore(root),true,(json,sig,channel,current,highest)->SignedManifest.verifyWithKeyForCheck(json,sig,channel,current,pair.getPublic()));}
  UpdateService.Downloads download(byte[] json,byte[] sig,boolean interrupt){return new UpdateService.Downloads(){public byte[] bytes(URI uri,int max){return uri.toString().endsWith(".sig")?sig:json;}public void file(SignedManifest.Asset asset,Path path,java.util.function.BooleanSupplier cancel,UpdateService.Progress progress)throws IOException{try(var out=Files.newOutputStream(path,StandardOpenOption.CREATE_NEW)){out.write(archive,0,archive.length/2);progress.accept(archive.length/2,archive.length);if(interrupt)throw new IOException("interrupted fixture");if(cancel.getAsBoolean())throw new InterruptedIOException();out.write(archive,archive.length/2,archive.length-archive.length/2);progress.accept(archive.length,archive.length);}}};}
  void await(UpdateService service,UpdateService.State state)throws Exception{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(5);while(System.nanoTime()<end){if(service.snapshot().state()==state)return;Thread.sleep(10);}fail("Expected "+state+", got "+service.snapshot().state());}
  @Test void manualCheckDownloadStatesRealProgressAndInstallFailure()throws Exception{byte[] json=JsonData.encode(doc()),sig=sign(json);List<UpdateService.Snapshot> events=new CopyOnWriteArrayList<>();try(UpdateService service=service(download(json,sig,false))){service.listener(events::add);service.check(false);await(service,UpdateService.State.AVAILABLE);service.download();await(service,UpdateService.State.READY_TO_INSTALL);assertTrue(events.stream().anyMatch(s->s.state()==UpdateService.State.DOWNLOADING&&s.downloaded()>0&&s.downloaded()<s.total()));assertTrue(events.stream().anyMatch(s->s.state()==UpdateService.State.VERIFYING));assertThrows(Exception.class,()->service.prepareInstall(root.resolve("missing-program"),ProcessHandle.current().pid(),0));assertEquals(UpdateService.State.FAILED,service.snapshot().state());}}
  @Test void interruptedDownloadLeavesOldBinaryAndRemovesPartial()throws Exception{byte[] json=JsonData.encode(doc()),sig=sign(json);Path old=root.resolve("AEGIS.exe");Files.writeString(old,"old-version");try(UpdateService service=service(download(json,sig,true))){service.check(true);await(service,UpdateService.State.FAILED);assertEquals("old-version",Files.readString(old));try(var paths=Files.list(root.resolve("updates"))){assertFalse(paths.anyMatch(p->p.toString().endsWith(".part")));}}}
  @Test void cancellationCannotReachReadyOrModifyInstallation()throws Exception{byte[] json=JsonData.encode(doc()),sig=sign(json);try(UpdateService service=service(download(json,sig,false))){service.listener(s->{if(s.state()==UpdateService.State.DOWNLOADING&&s.downloaded()>0)service.cancel();});service.check(true);await(service,UpdateService.State.FAILED);assertNotEquals(UpdateService.State.READY_TO_INSTALL,service.snapshot().state());}}
  @Test void invalidRuntimeSignatureCreatesNoAnnouncementOrFloor()throws Exception{byte[] json=JsonData.encode(doc());try(UpdateService service=service(download(json,new byte[64],false))){service.check(true);await(service,UpdateService.State.FAILED);assertNull(service.snapshot().manifest());assertFalse(Files.exists(root.resolve("updates/stable.floor")));}}
  @Test void signedOldFeedIsNotATransportErrorAndCannotDownloadOrLowerFloor()throws Exception{
    byte[] data=new String(JsonData.encode(doc()),StandardCharsets.UTF_8).replace("1.1.1","1.0.0").getBytes(StandardCharsets.UTF_8),signature=sign(data);
    UpdateStateStore store=new UpdateStateStore(root);Files.writeString(store.root().resolve("stable.floor"),"1.2.0\n");
    try(UpdateService service=service(download(data,signature,false))){CountDownLatch checked=new CountDownLatch(1);service.listener(s->{if(s.diagnostic()!=null)checked.countDown();});service.check(true);assertTrue(checked.await(5,TimeUnit.SECONDS));assertEquals(UpdateService.State.UP_TO_DATE,service.snapshot().state());assertNull(service.snapshot().manifest());assertFalse(service.snapshot().announcement());assertEquals("FEED_BEHIND_CLIENT",service.snapshot().diagnostic().code());service.download();assertEquals(UpdateService.State.UP_TO_DATE,service.snapshot().state());assertThrows(IOException.class,()->service.prepareInstall(root,1,0));}
    assertEquals("1.2.0\n",Files.readString(store.root().resolve("stable.floor")));assertFalse(Files.exists(store.root().resolve("stable-1.0.0.json")));
    SignedManifest old=SignedManifest.verifyWithKeyForCheck(data,signature,"stable","1.1.0",pair.getPublic());assertThrows(UpdateDiagnostic.Failure.class,()->old.requireInstallable("1.1.0","1.2.0"));
  }
  @Test void newlyAvailableFeedBelowRememberedFloorIsPolicyFailure()throws Exception{
    Files.createDirectories(root.resolve("updates"));Files.writeString(root.resolve("updates/stable.floor"),"1.2.0\n");byte[] data=JsonData.encode(doc());
    try(UpdateService service=service(download(data,sign(data),false))){service.check(true);await(service,UpdateService.State.FAILED);assertEquals(UpdateDiagnostic.Category.POLICY,service.snapshot().diagnostic().category());assertEquals("VERSION_ROLLBACK",service.snapshot().diagnostic().code());assertNull(service.snapshot().manifest());}
  }
  @Test void transportTlsSignatureAndSchemaDiagnosticsStaySeparateAndNeverLogRawMessages()throws Exception{
    for(int kind=0;kind<4;kind++){
      int selected=kind;byte[] valid=JsonData.encode(doc()),bad="not JSON".getBytes(StandardCharsets.UTF_8),badSignature=sign(bad);
      UpdateService.Downloads fixture=new UpdateService.Downloads(){public byte[] bytes(URI uri,int max)throws IOException{
        if(selected==0)throw new IOException("synthetic-password-token-cookie-plaintext");if(selected==1)throw new javax.net.ssl.SSLHandshakeException("synthetic-password-token-cookie-plaintext");
        return selected==2?(uri.toString().endsWith(".sig")?new byte[64]:valid):(uri.toString().endsWith(".sig")?badSignature:bad);
      }public void file(SignedManifest.Asset a,Path p,java.util.function.BooleanSupplier c,UpdateService.Progress pr){fail("Unverified data reached download");}};
      try(UpdateService service=service(fixture)){service.check(false);await(service,UpdateService.State.FAILED);assertEquals(List.of(UpdateDiagnostic.Category.TRANSPORT,UpdateDiagnostic.Category.TLS,UpdateDiagnostic.Category.SIGNATURE,UpdateDiagnostic.Category.SCHEMA).get(kind),service.snapshot().diagnostic().category());assertFalse(service.snapshot().message().contains("synthetic"));}
    }
    assertFalse(Files.readString(root.resolve("updates/diagnostic.log")).contains("synthetic-password"));
  }
  @Test void successfulInstallRequiresStartupAckAndRollsBackOnNoAck()throws Exception{Path old=root.resolve("AEGIS.AppImage"),candidate=root.resolve("download"),ack=root.resolve("confirmed");Files.writeString(old,"old");Files.writeString(candidate,"new");UpdateInstaller.replace(candidate,old,"token",ack,installed->{assertEquals("new",Files.readString(installed));Files.writeString(ack,"token\n");return true;},300);assertEquals("new",Files.readString(old));assertFalse(Files.exists(root.resolve("AEGIS.AppImage.old")));Files.delete(ack);Files.writeString(candidate,"next");assertThrows(IOException.class,()->UpdateInstaller.replace(candidate,old,"token",ack,p->true,100));assertEquals("new",Files.readString(old));assertFalse(Files.exists(root.resolve("AEGIS.AppImage.new")));}
  @Test void startupFailureRollsBackAndPreviousRecoveryCopyIsNeverOverwritten()throws Exception{Path old=root.resolve("AEGIS.AppImage"),candidate=root.resolve("download");Files.writeString(old,"old");Files.writeString(candidate,"new");assertThrows(IOException.class,()->UpdateInstaller.replace(candidate,old,"token",root.resolve("ack"),p->false,100));assertEquals("old",Files.readString(old));Files.writeString(root.resolve("AEGIS.AppImage.old"),"recovery");assertThrows(IOException.class,()->UpdateInstaller.replace(candidate,old,"token",root.resolve("ack"),p->true,100));assertEquals("recovery",Files.readString(root.resolve("AEGIS.AppImage.old")));}
}
