package org.securemail.client.update;
import static org.junit.jupiter.api.Assertions.*;
import com.google.gson.*;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import org.securemail.client.storage.AtomicFiles;
class UpdateEventsTest {
  @TempDir Path root;UpdateSecurityTest fixtures;UpdateEvents events;SignedManifest manifest;byte[] exact,sig;
  @BeforeEach void init()throws Exception{fixtures=new UpdateSecurityTest();fixtures.setup();exact=JsonData.encode(fixtures.doc());sig=fixtures.sign(exact);manifest=fixtures.verify(exact,sig);Path updates=root.resolve("updates");Files.createDirectories(updates);events=new UpdateEvents(updates,(j,s,c,v,h)->SignedManifest.verifyWithKeyForCheck(j,s,c,v,fixtures.pair.getPublic()));saveManifest("stable",exact,sig);}
  void saveManifest(String channel,byte[] j,byte[] s)throws Exception{AtomicFiles.write(root.resolve("updates/"+channel+"-"+manifest.version()+".json"),j);AtomicFiles.write(root.resolve("updates/"+channel+"-"+manifest.version()+".sig"),s);}
  Path job()throws Exception{Path job=root.resolve("updates/install-test");Files.createDirectories(job);JsonObject o=new JsonObject();o.addProperty("channel","stable");o.addProperty("version",manifest.version());o.addProperty("token","aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee");AtomicFiles.write(job.resolve("job.json"),JsonData.encode(o));AtomicFiles.write(job.resolve("manifest.json"),exact);AtomicFiles.write(job.resolve("manifest.sig"),sig);return job;}
  @Test void signedAvailableCreatesOfflineDeduplicatedLetter()throws Exception{events.record(manifest,UpdateEvents.Kind.AVAILABLE,"stable","");events.record(manifest,UpdateEvents.Kind.AVAILABLE,"stable","");assertEquals(1,events.history().size());assertTrue(events.history().getFirst().systemLetter());UpdateEvents reopened=new UpdateEvents(root.resolve("updates"),(j,s,c,v,h)->SignedManifest.verifyWithKeyForCheck(j,s,c,v,fixtures.pair.getPublic()));assertEquals(events.history(),reopened.history());}
  @Test void changedOrInvalidSignatureCannotCreateTrustedLetter()throws Exception{events.record(manifest,UpdateEvents.Kind.AVAILABLE,"stable","");sig[0]^=1;saveManifest("stable",exact,sig);assertTrue(events.history().isEmpty());assertThrows(java.io.IOException.class,()->events.record(null,UpdateEvents.Kind.AVAILABLE,"stable",""));}
  @Test void ackAndStartAloneNeverConfirmInstallation()throws Exception{Path job=job();AtomicFiles.write(job.resolve("confirmed"),"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\n".getBytes());assertTrue(events.history().isEmpty());AtomicFiles.write(job.resolve("installed"),manifest.version().getBytes());var h=events.history();assertEquals(2,h.size());assertEquals(1,h.stream().filter(UpdateEvents.Event::systemLetter).count());assertTrue(h.stream().anyMatch(e->e.kind()==UpdateEvents.Kind.INSTALLED));assertEquals(h,events.history());}
  @Test void wrongAckTokenAndRollbackPreventInstalledLetter()throws Exception{Path job=job();AtomicFiles.write(job.resolve("confirmed"),"wrong".getBytes());AtomicFiles.write(job.resolve("installed"),manifest.version().getBytes());assertTrue(events.history().isEmpty());AtomicFiles.write(job.resolve("rolled-back"),new byte[]{1});AtomicFiles.write(job.resolve("failed"),new byte[]{1});assertTrue(events.history().stream().noneMatch(UpdateEvents.Event::systemLetter));assertTrue(events.history().stream().anyMatch(e->e.kind()==UpdateEvents.Kind.ROLLBACK));}
  @Test void errorsContainOnlyCodesAndNoPrivilegedSender()throws Exception{events.record(null,UpdateEvents.Kind.FAILED,"stable","TLS_FAILED");assertFalse(events.history().getFirst().systemLetter());assertThrows(java.io.IOException.class,()->events.record(null,UpdateEvents.Kind.FAILED,"stable","password=secret"));assertFalse(UpdateEvents.class.getName().startsWith("org.securemail.protocol"));assertNotEquals(UpdateEvents.Event.class,org.securemail.client.crypto.PlainMessage.class);}
  @Test void stableAndBetaIdsDoNotCollide()throws Exception{events.record(manifest,UpdateEvents.Kind.AVAILABLE,"stable","");JsonObject beta=fixtures.doc();beta.addProperty("channel","beta");byte[] j=JsonData.encode(beta),s=fixtures.sign(j);SignedManifest b=SignedManifest.verifyWithKeyForCheck(j,s,"beta","0.0.0",fixtures.pair.getPublic());saveManifest("beta",j,s);events.record(b,UpdateEvents.Kind.AVAILABLE,"beta","");assertEquals(2,events.history().size());assertNotEquals(UpdateEvents.id(manifest.version(),"stable",UpdateEvents.Kind.AVAILABLE),UpdateEvents.id(manifest.version(),"beta",UpdateEvents.Kind.AVAILABLE));}
}
